@baseUrl=http://localhost:8000/api/v1
### Boards

# @name createNewBoard
POST {{baseUrl}}/boards HTTP/1.1
Content-Type: application/json

{
  "title": "Hello world board"
}

### Columns

# @name createNewColumn
POST {{baseUrl}}/columns HTTP/1.1
Content-Type: application/json

{
  "boardId": "617534395d7724d503803c82",
  "title": "Hello world column"
}


###

# @name updateColumn
PUT {{baseUrl}}/columns/617534425d7724d503803c83 HTTP/1.1
Content-Type: application/json

{
  "title": "Hello world update"
}

### Cars

# @name createNewColumn
POST {{baseUrl}}/cards HTTP/1.1
Content-Type: application/json

{
  "boardId": "617534395d7724d503803c82",
  "columnId": "617534425d7724d503803c83",
  "title": "Hello world card"
}


# # @name update
# PATCH {{baseUrl}}/{{resourceName}}/KkSXxPt
# Content-Type: application/json

# {
#   "name": "Tasty Plastic Chips Update",
#   "color": "red",
#   "price": 950
# }

# ###

# # @name remove
# DELETE {{baseUrl}}/{{resourceName}}/2