@baseUrl=http://localhost:8000/api/v1

### Boards ###

# @name createNewBoard
POST {{baseUrl}}/boards HTTP/1.1
Content-Type: application/json

{
  "title": "New board"
}

###

# @name getFullBoard
GET  {{baseUrl}}/boards/6176bfe63144a90cc8c10694 HTTP/1.1

### Columns ###

# @name createNewColumn
POST {{baseUrl}}/columns HTTP/1.1
Content-Type: application/json

{
  "boardId": "6176bfe63144a90cc8c10694",
  "title": "Column 1"
}

###

# @name updateColumn
PUT {{baseUrl}}/columns/61767f28c6f1b7659c916be7 HTTP/1.1
Content-Type: application/json

{
  "_id": "61767f28c6f1b7659c916be7",
  "boardId": "617553cbd5ada8f2c313f7e4",
  "title": "column 1",
  "cardOrder": [
    "61767f2cc6f1b7659c916be8"
  ],
  "createdAt": 1635155121424,
  "updatedAt": null,
  "_destroy": true
}

###

# @name removeColumn
PUT {{baseUrl}}/columns/61767f28c6f1b7659c916be7 HTTP/1.1
Content-Type: application/json

{
  "_id": "61767f28c6f1b7659c916be7",
  "boardId": "617553cbd5ada8f2c313f7e4",
  "title": "column 1",
  "cardOrder": [
    "61767f2cc6f1b7659c916be8"
  ],
  "createdAt": 1635155121424,
  "updatedAt": null,
  "_destroy": true
}

### Cars ###

# @name createNewCard
POST {{baseUrl}}/cards HTTP/1.1
Content-Type: application/json

{
  "boardId": "617553cbd5ada8f2c313f7e4",
  "columnId": "61755e24b8018dda2e182971",
  "title": "Card 1"
}


# # @name update
# PATCH {{baseUrl}}/{{resourceName}}/KkSXxPt
# Content-Type: application/json

# {
#   "name": "Tasty Plastic Chips Update",
#   "color": "red",
#   "price": 950
# }

# ###

# # @name remove
# DELETE {{baseUrl}}/{{resourceName}}/2